#!/usr/bin/env bash
CURRPATH=$(pwd)
PARAMS=""
for var in "$@"
do
    PARAMS=${PARAMS}~"$var"
done

if [ -n "$1" ]
then
	if [ "$1" == "run" ]
	then
#		echo $(dirname $0)/lib/ext/railo-cli.jar
		cd $(dirname $0)
		java -jar lib/ext/railo-cli.jar -webroot=$CURRPATH uri=$2?$3
		
	elif [ "$1" == "start" ]
	then
		cd $(dirname $0)
		java -jar -DSTOP.PORT=8887 -DSTOP.KEY=railo -Xms256M  -Xmx512M lib/start.jar -Drailo.webroot=$CURRPATH	--exec	
		
	elif [ "$1" == "stop" ]
	then
	#echo "Starging up Railo as a server"
		cd $(dirname $0)
		java -jar -DSTOP.PORT=8887 -DSTOP.KEY=railo lib/start.jar --stop	
		
	else
		echo "Calling plugin $1"
		cd $(dirname $0)
		java -jar lib/ext/railo-cli.jar -webroot=./webroot/ -uri='/runner.cfm?currentpath='${CURRPATH}'&params='$PARAMS

	fi
else
	cd $(dirname $0)
	java -jar lib/ext/railo-cli.jar -webroot=./webroot/ -uri='/help.cfm'
fi
#java -jar ./lib/ext/railo-cli.jar -webroot=./webroot/ -uri='/runner.cfm?currentpath='${CURRPATH}'&params='$PARAMS
